version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password123
      MARIADB_DATABASE: app
      MARIADB_USER: tester
      MARIADB_PASSWORD: tester228
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'
    expose:
      - 3306
#  web:
#    image: openjdk:17-oracle
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    expose:
#      - 8080
#    volumes:
#      - ./build/libs/MLKitAPI.jar:/MLKitAPI.jar
#      - ./secret.properties:/secret.properties
#    command: java -jar MLKitAPI.jar --spring.datasource.url=jdbc:mariadb://mlkit-db:3306/mlkit