version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password123
      MARIADB_DATABASE: app
      MARIADB_USER: tester
      MARIADB_PASSWORD: tester228
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'
    expose:
      - 3306
    restart: always
  web:
    image: openjdk:17-oracle
    depends_on:
      - db
    working_dir: /server
    volumes:
      - ./build/libs/AdolfServer.jar:/server/AdolfServer.jar
      - ./certificate.p12:/server/certificate.p12
    command: java -jar /server/AdolfServer.jar --spring.datasource.url=jdbc:mariadb://db:3306/app
    ports:
      - '8443:8443'
    expose:
      - 8443
    restart: always