-- REGISTRATION
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_name VARCHAR(32) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    token VARCHAR(255) NOT NULL,
    mask VARCHAR(4) NOT NULL,
    creation_time DATETIME NOT NULL,
    expiration_time DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `groups` (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS lessons (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    group_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    hours INTEGER NOT NULL,
    passed_hours INTEGER NOT NULL
    FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lessons_history (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    lesson_id INTEGER NOT NULL,
    number INTEGER NOT NULL,
    date DATE NOT NULL,
    topic VARCHAR(255),
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
);